---
  mysql_root_password: root!1234pwdA$76883IR
  wordpressdb: wpdb
  cluster_user: cluster_user
  cluster_passwd: clusterpwd!1234A$76883IR
  wp_db_user: wpuser
  wp_db_passwd: wpuserpwd!1234A$76883IR
  



