---
- name: Install rsyslog
  dnf:
    name: rsyslog
    state: latest


- name: mySQL my.cnf
  template:
     src: rsyslog.conf.j2
     dest: "/etc/rsyslog.conf"
     owner: root
     group: root
     mode: 0644

- name: Rsyslog restart
  systemd:
    name: rsyslog
    state: restarted



