---

- name: Setup haproxy
  dnf:
    name: haproxy
    state: present

- name: Setup config for haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg


- name: Restart haproxy
  service:
    name: haproxy
    state: restarted
    enabled: yes

